
# Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lostArk?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: #database connection pool
      connection-test-query: 'select 1'
      connection-timeout: 10000 # 10 sec.
      maximum-pool-size: 10
      pool-name: smart-server-pool
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true# Database
    generate-ddl: true
  rabbitmq:
    host : localhost
    port : 5672
    username : guest
    password : guest
  data:
    redis:
      host: localhost
      port: 6379
loa:
  apiKey: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IktYMk40TkRDSTJ5NTA5NWpjTWk5TllqY2lyZyIsImtpZCI6IktYMk40TkRDSTJ5NTA5NWpjTWk5TllqY2lyZyJ9.eyJpc3MiOiJodHRwczovL2x1ZHkuZ2FtZS5vbnN0b3ZlLmNvbSIsImF1ZCI6Imh0dHBzOi8vbHVkeS5nYW1lLm9uc3RvdmUuY29tL3Jlc291cmNlcyIsImNsaWVudF9pZCI6IjEwMDAwMDAwMDAwNzcxMTEifQ.cmXAuy1f2WE1Hok9ROfKGqseN0nuZ5VjFz9nMAWnpCo5IBBo1HVwNy8kx-mWraL6rD-QnmJLNUVH4CKGqRXVxaJQy8ShA_m29Juf4FNlYn65jm91igJQB0bk-qk_OZzLpew1HZYVyvi6qDk-SHcYcNIRd563WP2mcXXEHBIIml-PtlTdWG1-JjE_rM-1Y_VlIXtzW8uNEXGExgqZQuzmA8ACEZqIdw1csYvGrW5ocmCAoJTlCIClC7F9Om45gCVF0dMuuqz9Ky5bS9Lr933zJibTERbIJQig9eckw9_vi_4YPFQR27z5xTg6atfOgmr9CtJOOpy5XuuF8Kg1-GQoMQ
server:
  port: 1234